version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip install --upgrade pip
  pre_build:
    commands:
      - echo "Installing dependencies and executing unit tests - `pwd`"
      - cd deployment
      - chmod +x ./run-unit-tests.sh && ./run-unit-tests.sh
      - echo "Installing dependencies and executing unit tests completed `date`"
  build:
    commands:
      - echo "`pwd`"
      - echo "Starting build `date` in `pwd`"
      - chmod +x ./build-s3-dist.sh && ./build-s3-dist.sh $DIST_OUTPUT_BUCKET $SOLUTION_NAME $VERSION
      - echo "Build completed `date`"

  post_build:
    commands:
      - echo "Retrieving next stage buildspec `date` in `pwd`"
      - aws s3 cp s3://solutions-build-assets/changelog-spec.yml ../buildspec.yml
      - echo "Retrieving next stage buildspec complete"
      - echo "Post build completed on `date`"
      - mkdir -p open-source
      - touch open-source/source-is-on-github

artifacts:
  files:
      - deployment/**/*
      - source/**/*
      - buildspec.yml
      - CHANGELOG.md
      - sonar-project.properties
