# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = [""]
exclude = [
     "tests"
]

[project]
name = "InstanceScheduler-Lambda"
version = "1.5"
description = "AWS Instance Scheduler"

dependencies = [
    "pytz",
    "requests",
    "chardet",
]

[project.optional-dependencies]
dev = [
    "tox",
    "boto3-stubs-lite[essential]",
    "boto3-stubs-lite[ssm]",
    "botocore>=1.12.99",
    "boto3>=1.9.99",
    "mock>=2.0.0",
    "pytest>=7.2.0",
    "pytest-cov>=4.0.0",
    "pytest-mock>=1.10.4",
    "pytest-runner>=2.11.1",
    "uuid>=1.30",
    "moto>=1.3.14",
    "freezegun>=0.3.15"
]
